Vagrant::Config.run do |config|
  config.vm.box = "ubuntu-12.10"
  config.vm.box_url = "http://cloud-images.ubuntu.com/quantal/current/quantal-server-cloudimg-vagrant-amd64-disk1.box"

  config.vm.define :vm_1 do |vm_1_config|
    vm_1_config.vm.network :hostonly, '192.168.1.10'
  end

  config.vm.define :vm_2 do |vm_2_config|
    vm_2_config.vm.network :hostonly, '192.168.1.10'
  end
end
